"""Descripción del cambio

Revision ID: 1a41be801059
Revises: 2cbeec8fafe7
Create Date: 2025-09-28 22:47:59.248842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a41be801059'
down_revision = '2cbeec8fafe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_generales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_ofertas', sa.Integer(), nullable=True),
    sa.Column('promedio_compatibilidad', sa.Float(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_modalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('conteo', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_tecnologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tecnologia', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('conteo', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.String(length=255), nullable=False),
    sa.Column('conteo', sa.Integer(), nullable=True),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metricas_ubicacion')
    op.drop_table('metricas_tecnologia')
    op.drop_table('metricas_modalidad')
    op.drop_table('metricas_generales')
    # ### end Alembic commands ###
