"""Add url and compatibilidad to AnalisisResultado

Revision ID: 2cbeec8fafe7
Revises: c088157fc3a4
Create Date: 2025-09-24 13:28:12.595564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbeec8fafe7'
down_revision = 'c088157fc3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('compatibilidad', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_resultados', schema=None) as batch_op:
        batch_op.drop_column('compatibilidad')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
