"""Creando tablas de ofertas, busquedas y notas

Revision ID: 4487d8d856e1
Revises: 
Create Date: 2025-09-19 18:03:43.258675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4487d8d856e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busquedas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termino', sa.String(length=255), nullable=True),
    sa.Column('filtros', sa.JSON(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('ofertas')
    op.drop_table('busquedas')
    # ### end Alembic commands ###
