"""add analisis_oferta and tecnologias tables

Revision ID: 7a427a45578d
Revises: e183fe05d864
Create Date: 2025-09-24 10:01:54.758036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a427a45578d'
down_revision = 'e183fe05d864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_tecnologia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('analisis_ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_analisis', sa.DateTime(), nullable=True),
    sa.Column('ciudad', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oferta_id')
    )
    op.create_table('tecnologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_tecnologia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ofertas_tecnologias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('tecnologia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['tecnologia_id'], ['tecnologias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas_tecnologias')
    op.drop_table('tecnologias')
    op.drop_table('analisis_ofertas')
    op.drop_table('categorias_tecnologia')
    # ### end Alembic commands ###
