"""add analisis_resultados table

Revision ID: c088157fc3a4
Revises: 7a427a45578d
Create Date: 2025-09-24 10:20:23.874434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c088157fc3a4'
down_revision = '7a427a45578d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('ciudad', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('lenguajes', sa.Text(), nullable=True),
    sa.Column('frameworks', sa.Text(), nullable=True),
    sa.Column('librerias', sa.Text(), nullable=True),
    sa.Column('bases_datos', sa.Text(), nullable=True),
    sa.Column('nube_devops', sa.Text(), nullable=True),
    sa.Column('control_versiones', sa.Text(), nullable=True),
    sa.Column('arquitectura_metodologias', sa.Text(), nullable=True),
    sa.Column('integraciones', sa.Text(), nullable=True),
    sa.Column('inteligencia_artificial', sa.Text(), nullable=True),
    sa.Column('ofimatica_gestion', sa.Text(), nullable=True),
    sa.Column('ciberseguridad', sa.Text(), nullable=True),
    sa.Column('marketing_digital', sa.Text(), nullable=True),
    sa.Column('erp_lowcode', sa.Text(), nullable=True),
    sa.Column('fecha_analisis', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analisis_resultados')
    # ### end Alembic commands ###
