"""Add nivel_score to AnalisisResultado

Revision ID: c91a729e6656
Revises: 1a41be801059
Create Date: 2025-10-01 10:57:22.803017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91a729e6656'
down_revision = '1a41be801059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_resultados', schema=None) as batch_op:
        batch_op.drop_column('nivel_score')

    # ### end Alembic commands ###
