"""add raw_fecha to Oferta

Revision ID: e183fe05d864
Revises: 1cfb2136f051
Create Date: 2025-09-22 10:56:54.168115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e183fe05d864'
down_revision = '1cfb2136f051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_fecha', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_column('raw_fecha')

    # ### end Alembic commands ###
